-- Sample scholarship data — run after schema.sql in the Supabase SQL editor

insert into public.scholarships (title, country, field, degree_level, deadline, link, description, eligibility) values

-- United States
('Fulbright Foreign Student Program', 'United States', 'Arts & Humanities', 'masters', '2026-10-01', 'https://foreign.fulbrightonline.org/', 'Flagship US exchange program covering tuition, living expenses, and health insurance for graduate study.', 'Open to citizens of participating countries outside the US. Applicants must hold a bachelor''s degree or equivalent, demonstrate English proficiency, and show strong academic and leadership records. US citizenship or permanent residency is not eligible. Selected candidates must commit to returning to their home country after completion.'),

('NSF Graduate Research Fellowship', 'United States', 'Natural Sciences', 'phd', '2026-10-15', 'https://www.nsfgrfp.org/', 'Three years of support for graduate research in STEM fields. Includes $37,000 annual stipend.', 'Open to US citizens, nationals, and permanent residents who are in the early stages of their graduate study (first or second year). Applicants must be pursuing a research-based master''s or doctoral degree in an NSF-supported STEM field. Students who have completed more than 12 months of graduate study are ineligible.'),

('Gates Millennium Scholars Program', 'United States', 'Computer Science', 'undergraduate', '2026-12-15', 'https://gmsp.org/', 'Full scholarship for outstanding minority students pursuing STEM disciplines.', 'Applicants must be African American, American Indian/Alaska Native, Asian Pacific Islander American, or Hispanic American; be a US citizen, national, or permanent resident; maintain a cumulative GPA of 3.3 or above; and demonstrate significant financial need as defined by federal guidelines.'),

('Knight-Hennessy Scholars', 'United States', 'Public Policy', 'masters', '2026-10-01', 'https://knight-hennessy.stanford.edu/', 'Full funding for graduate study at Stanford University. Open to all fields.', 'Open to applicants worldwide who have received their first undergraduate degree within the past seven years. Applicants must be admitted to a Stanford graduate degree programme. There are no restrictions on nationality, field of study, age, or professional background. Selection is based on independence of thought, purposeful leadership, and civic mindset.'),

-- United Kingdom
('Chevening Scholarships', 'United Kingdom', 'Public Policy', 'masters', '2026-11-05', 'https://www.chevening.org/', 'UK government scholarship for future global leaders. Covers tuition, living, and travel.', 'Applicants must be citizens of a Chevening-eligible country, have at least two years of work experience, hold an undergraduate degree that will gain entry to a UK university, and be able to return to their home country for a minimum of two years after the scholarship ends. Previous Chevening Scholars and current UK residents are not eligible.'),

('Rhodes Scholarship', 'United Kingdom', 'Arts & Humanities', 'masters', '2026-08-01', 'https://www.rhodeshouse.ox.ac.uk/', 'Fully funded postgraduate study at the University of Oxford for exceptional students worldwide.', 'Open to young people from eligible countries who are typically between 18–28 years of age (varies by constituency). Candidates must demonstrate intellectual distinction, character, leadership, and commitment to service. Applicants must hold or expect to hold a bachelor''s degree before taking up the scholarship. Married candidates may apply.'),

('Commonwealth Scholarship', 'United Kingdom', 'Medicine & Health', 'phd', '2026-12-01', 'https://cscuk.fcdo.gov.uk/', 'Full scholarships for citizens of Commonwealth countries to study in the UK.', 'Open to citizens and permanent residents of Commonwealth countries who are applying to study at a UK university. Applicants must be available to take up the scholarship by the start of the UK academic year, be unable to pursue the study without the scholarship, and hold a first degree of at least upper second class (2:1) standard.'),

-- Germany
('DAAD Scholarship', 'Germany', 'Engineering', 'masters', '2026-11-15', 'https://www.daad.de/en/', 'German Academic Exchange Service funding for international students at German universities.', 'Open to international students who hold an above-average bachelor''s degree. Applicants typically need at least two years of professional experience after completing their first academic degree. German language skills may be required depending on the programme. Applications must be submitted through the applicant''s home country DAAD office.'),

('Konrad-Adenauer-Stiftung Scholarship', 'Germany', 'Social Sciences', 'phd', '2026-07-15', 'https://www.kas.de/en/', 'Funding for outstanding doctoral students with a focus on political and social sciences.', 'Open to German and foreign students enrolled in or applying for a doctoral programme at a German university. Applicants must demonstrate above-average academic performance, social commitment, and alignment with democratic and Christian-democratic values. Foreign applicants must have a strong command of German.'),

-- Australia
('Australia Awards Scholarships', 'Australia', 'Agriculture', 'masters', '2026-04-30', 'https://www.australiaawards.gov.au/', 'Long-term development awards for students from developing countries to study in Australia.', 'Open to citizens of eligible countries in the Indo-Pacific region, Africa, and the Middle East. Applicants must not hold Australian or New Zealand citizenship or permanent residency, must be outside Australia at the time of application, and must commit to returning to their home country for at least two years after completing their studies.'),

('Endeavour Leadership Program', 'Australia', 'Environmental Science', 'phd', '2026-06-30', 'https://internationaleducation.gov.au/', 'Merit-based scholarships for high achieving students to undertake study or research in Australia.', 'Open to citizens of eligible countries in the Asia-Pacific, Middle East, Europe, and Americas regions. Applicants must not be Australian citizens or permanent residents. Candidates must demonstrate high academic achievement and the capacity to contribute to their community. The scholarship requires full-time enrolment at an Australian institution.'),

-- Canada
('Vanier Canada Graduate Scholarships', 'Canada', 'Medicine & Health', 'phd', '2026-11-01', 'https://vanier.gc.ca/', '$50,000 per year for three years for doctoral students demonstrating leadership skills.', 'Open to both Canadian and international students who are nominated by a Canadian university. Candidates must be pursuing their first doctoral degree, have an overall average of at least A- in the last two completed years of study, and demonstrate leadership ability and a high standard of scholarly achievement in graduate and undergraduate studies.'),

('Trudeau Foundation Scholarship', 'Canada', 'Social Sciences', 'phd', '2026-12-01', 'https://www.trudeaufoundation.ca/', 'Three years of support for doctoral research that engages with Canadian society.', 'Open to Canadian citizens, permanent residents, and protected persons enrolled in or applying to a doctoral programme at a Canadian university. Research must engage with at least one of the Foundation''s four thematic areas. Applicants must demonstrate academic excellence, social commitment, and a vision for Canada''s role in the world.'),

-- Netherlands
('Holland Scholarship', 'Netherlands', 'Business', 'masters', '2027-01-31', 'https://www.studyinholland.nl/scholarships/', 'EUR 5,000 grant for international students from outside the EEA starting a Bachelor or Master program.', 'Open to non-EEA international students who are applying to a full-time bachelor''s or master''s programme at a participating Dutch research university or university of applied sciences. Applicants must be applying for the first time to a Dutch higher education institution. Previous degree holders from the Netherlands are not eligible.'),

('Leiden Excellence Scholarship', 'Netherlands', 'Law', 'masters', '2026-09-01', 'https://www.universiteitleiden.nl/scholarships/', 'Partial or full tuition scholarships for excellent non-EEA students at Leiden University.', 'Open to non-EEA students who have been admitted to a Leiden University English-taught master''s programme. Applicants must have completed a bachelor''s degree with outstanding academic results (typically a GPA in the top 10% of their class). The scholarship cannot be combined with other Leiden University scholarships.'),

-- Japan
('MEXT Scholarship', 'Japan', 'Engineering', 'masters', '2026-05-31', 'https://www.studyinjapan.go.jp/en/stype/mext/', 'Japanese government scholarship covering tuition, monthly stipend, and travel for research students.', 'Open to nationals of countries with diplomatic relations with Japan. Applicants must be under 35 years of age (for research students), have completed or be completing undergraduate education, and demonstrate Japanese language ability or willingness to learn. Applications are submitted via the Japanese Embassy in the applicant''s home country.'),

('JASSO Honors Scholarship', 'Japan', 'Natural Sciences', 'phd', '2026-08-31', 'https://www.jasso.or.jp/en/', 'Monthly scholarship for international students enrolled in Japanese universities.', 'Open to international students currently enrolled at a Japanese university as regular students. Candidates must demonstrate excellent academic performance, strong conduct, and financial need. Recipients must maintain satisfactory academic progress throughout the scholarship period and must not be receiving other Japanese government scholarships simultaneously.'),

-- Switzerland
('Swiss Government Excellence Scholarships', 'Switzerland', 'Natural Sciences', 'phd', '2026-12-15', 'https://www.sbfi.admin.ch/scholarships/', 'Research scholarships and postdoctoral fellowships for foreign scholars at Swiss universities.', 'Open to citizens of eligible countries who hold a master''s degree (for PhD applicants) or a PhD (for postdoctoral applicants). Candidates must be no older than 35 years for PhD scholarships and 45 years for postdoctoral fellowships. Swiss citizens and current residents of Switzerland are not eligible. Applications are submitted through the Swiss Embassy.'),

-- Sweden
('Swedish Institute Scholarships', 'Sweden', 'Environmental Science', 'masters', '2027-02-10', 'https://si.se/en/apply/scholarships/', 'Full scholarships for global professionals to study a one or two-year master in Sweden.', 'Open to citizens of eligible countries in Asia, Africa, the Middle East, Eastern Europe, and Latin America. Applicants must have a bachelor''s degree, at least 3,000 hours of work experience, and demonstrate leadership potential and a commitment to contributing to sustainable development in their home country after completing the degree.'),

-- Singapore
('NUS Research Scholarship', 'Singapore', 'Computer Science', 'phd', '2027-03-01', 'https://nusgs.nus.edu.sg/scholarships/', 'Full tuition, monthly stipend, and housing allowance for PhD research at the National University of Singapore.', 'Open to both Singapore citizens and international applicants who have been admitted to an NUS PhD programme. Applicants must hold a good bachelor''s degree with honours (upper second class or equivalent) or a master''s degree in a relevant field. Proficiency in English is required. The scholarship is tenable for up to four years subject to satisfactory academic progress.');
