-- Sample scholarship data — run after schema.sql in the Supabase SQL editor
-- Uses ON CONFLICT so re-running updates existing rows rather than failing

insert into public.scholarships (title, country, field, degree_level, deadline, link, description, eligibility) values

-- United States
('Fulbright Foreign Student Program', 'United States', 'Arts & Humanities', 'masters', '2026-10-01', 'https://foreign.fulbrightonline.org/', 'The Fulbright Foreign Student Program is the United States government''s flagship international exchange scholarship, administered by the U.S. Department of State. It enables graduate students, artists, and young professionals from abroad to study and conduct research in the United States for one to two academic years. The program covers full tuition fees, a monthly living stipend, health insurance, and round-trip airfare, allowing scholars to fully concentrate on their academic and professional development. Beyond funding, Fulbright Scholars join a global network of over 400,000 alumni across more than 160 countries, including heads of state, Nobel laureates, and leading scientists. The program places strong emphasis on mutual understanding between cultures, and scholars are expected to serve as ambassadors of their home countries while in the US.', 'Open to citizens of participating countries outside the US. Applicants must hold a bachelor''s degree or equivalent, demonstrate English proficiency, and show strong academic and leadership records. US citizenship or permanent residency is not eligible. Selected candidates must commit to returning to their home country after completion.'),

('NSF Graduate Research Fellowship', 'United States', 'Natural Sciences', 'phd', '2026-10-15', 'https://www.nsfgrfp.org/', 'The National Science Foundation Graduate Research Fellowship Program (NSF GRFP) is one of the most prestigious graduate fellowships in the United States, providing three years of financial support within a five-year fellowship period. Fellows receive an annual stipend of $37,000 and a $16,000 cost-of-education allowance paid to their institution. The fellowship supports outstanding graduate students in NSF-supported STEM disciplines who are pursuing research-based master''s and doctoral degrees. NSF Fellows are recognized by universities, industry, and government as among the most promising scientists and engineers emerging from the US. Recipients gain access to international research and professional development opportunities through supplemental funding programs and collaborations with national laboratories.', 'Open to US citizens, nationals, and permanent residents who are in the early stages of their graduate study (first or second year). Applicants must be pursuing a research-based master''s or doctoral degree in an NSF-supported STEM field. Students who have completed more than 12 months of graduate study are ineligible.'),

('Gates Millennium Scholars Program', 'United States', 'Computer Science', 'undergraduate', '2026-12-15', 'https://gmsp.org/', 'The Gates Millennium Scholars (GMS) Program, funded by the Bill & Melinda Gates Foundation, provides outstanding minority students with full scholarships to pursue undergraduate and graduate degrees in any discipline, with a particular focus on STEM fields. The scholarship covers full unmet financial need — including tuition, room, board, books, and personal expenses — for the duration of the recipient''s undergraduate studies. High-achieving scholars may also receive funding to continue into graduate programs in computer science, education, engineering, library science, mathematics, public health, or science. The program also provides a robust leadership development component, connecting scholars with mentors, internship opportunities, and a network of over 20,000 GMS alumni who span every major sector. Selection is highly competitive; the program aims to develop the next generation of diverse American leaders.', 'Applicants must be African American, American Indian/Alaska Native, Asian Pacific Islander American, or Hispanic American; be a US citizen, national, or permanent resident; maintain a cumulative GPA of 3.3 or above; and demonstrate significant financial need as defined by federal guidelines.'),

('Knight-Hennessy Scholars', 'United States', 'Public Policy', 'masters', '2026-10-01', 'https://knight-hennessy.stanford.edu/', 'Knight-Hennessy Scholars is one of the world''s largest fully endowed graduate scholarship programs, housed at Stanford University and funded by a $750 million gift from Phil Knight and his family. Up to 100 scholars are selected annually from around the world to pursue any graduate degree at Stanford, including joint and dual degrees across law, business, medicine, engineering, education, and the arts. The program provides full tuition, a living stipend, travel, and a one-time enrichment fund for each scholar throughout their Stanford studies. Beyond funding, scholars participate in a three-year leadership curriculum designed to cultivate collaborative, courageous, and innovative leaders equipped to address the world''s most complex challenges. The cohort-based model fosters lifelong connections across disciplines and nationalities.', 'Open to applicants worldwide who have received their first undergraduate degree within the past seven years. Applicants must be admitted to a Stanford graduate degree programme. There are no restrictions on nationality, field of study, age, or professional background. Selection is based on independence of thought, purposeful leadership, and civic mindset.'),

-- United Kingdom
('Chevening Scholarships', 'United Kingdom', 'Public Policy', 'masters', '2026-11-05', 'https://www.chevening.org/', 'Chevening Scholarships are the UK government''s flagship international scholarship programme, funded by the Foreign, Commonwealth & Development Office and partner organisations. The programme offers full financial support for a one-year master''s degree at any UK university to outstanding emerging leaders from around the world. Chevening covers tuition fees, a monthly living allowance, travel to and from the UK, and an arrival and departure allowance. Since its establishment in 1983, more than 50,000 Chevening Scholars have graduated from the programme and gone on to become presidents, prime ministers, Nobel Prize winners, prominent journalists, and leading academics. Scholars gain access to an exclusive global alumni network and are expected to return home after their studies to contribute to national development and maintain lasting connections with the UK.', 'Applicants must be citizens of a Chevening-eligible country, have at least two years of work experience, hold an undergraduate degree that will gain entry to a UK university, and be able to return to their home country for a minimum of two years after the scholarship ends. Previous Chevening Scholars and current UK residents are not eligible.'),

('Rhodes Scholarship', 'United Kingdom', 'Arts & Humanities', 'masters', '2026-08-01', 'https://www.rhodeshouse.ox.ac.uk/', 'The Rhodes Scholarship is the oldest and arguably most prestigious international scholarship programme in the world, established in 1902 under the will of Cecil John Rhodes. It funds postgraduate study at the University of Oxford for exceptional students from more than 60 countries, covering all university and college fees, a personal stipend, and a travel allowance. Rhodes Scholars are chosen not solely for their outstanding scholarly achievements but for their character, commitment to others and to the common good, and potential for leadership in whatever domains their careers may take them. Most scholars pursue one or two years of study at Oxford; some go on to doctoral research. Among the programme''s distinguished alumni are US Presidents, Prime Ministers, Supreme Court justices, Nobel laureates, and leaders across business, science, and the arts.', 'Open to young people from eligible countries who are typically between 18–28 years of age (varies by constituency). Candidates must demonstrate intellectual distinction, character, leadership, and commitment to service. Applicants must hold or expect to hold a bachelor''s degree before taking up the scholarship. Married candidates may apply.'),

('Commonwealth Scholarship', 'United Kingdom', 'Medicine & Health', 'phd', '2026-12-01', 'https://cscuk.fcdo.gov.uk/', 'Commonwealth Scholarships are funded by the UK government and offered to citizens of Commonwealth countries to pursue postgraduate study or research in the United Kingdom. The scholarships are administered by the Commonwealth Scholarship Commission (CSC) and aim to contribute to the UK''s international development goals by building the capacity of talented individuals who will make a difference in their home countries. The award covers university tuition fees, a monthly living allowance, a travel grant, and an arrival allowance. In the field of Medicine and Health, scholars typically conduct PhD research at leading UK universities including Oxford, Cambridge, Imperial College London, and the London School of Hygiene and Tropical Medicine. The programme prioritises candidates whose studies are aligned with development needs in their home country.', 'Open to citizens and permanent residents of Commonwealth countries who are applying to study at a UK university. Applicants must be available to take up the scholarship by the start of the UK academic year, be unable to pursue the study without the scholarship, and hold a first degree of at least upper second class (2:1) standard.'),

-- Germany
('DAAD Scholarship', 'Germany', 'Engineering', 'masters', '2026-11-15', 'https://www.daad.de/en/', 'The German Academic Exchange Service (DAAD) is the world''s largest funding organisation for the international exchange of students and researchers. DAAD scholarships enable international graduates and postgraduates to pursue master''s degrees or conduct research at German universities and research institutions for periods ranging from one month to two years. The scholarship covers a monthly stipend to cover living expenses, health insurance, and in some programmes, travel costs and a study and research allowance. Germany is home to some of the world''s top-ranked engineering institutions, including TU Munich, RWTH Aachen, and KIT, making DAAD an exceptional gateway to world-class technical education. The scholarship is available in both English-taught and German-taught programmes, and DAAD offers intensive German language courses to prepare recipients before their studies begin.', 'Open to international students who hold an above-average bachelor''s degree. Applicants typically need at least two years of professional experience after completing their first academic degree. German language skills may be required depending on the programme. Applications must be submitted through the applicant''s home country DAAD office.'),

('Konrad-Adenauer-Stiftung Scholarship', 'Germany', 'Social Sciences', 'phd', '2026-07-15', 'https://www.kas.de/en/', 'The Konrad-Adenauer-Stiftung (KAS) Scholarship Programme supports academically gifted doctoral students at German universities who demonstrate a strong commitment to the social and political principles of Christian democracy. Funded by the German government, KAS scholarships are awarded to both German and international students whose research focuses on political science, sociology, law, economics, or related social sciences. Recipients receive a monthly stipend, additional family allowances where applicable, and a book and material allowance. Beyond financial support, KAS organises an extensive programme of seminars, conferences, workshops, and international study trips that connect scholars with leading thinkers, politicians, and practitioners. Scholars become part of a global network of alumni who share a commitment to democracy, the rule of law, and a united Europe.', 'Open to German and foreign students enrolled in or applying for a doctoral programme at a German university. Applicants must demonstrate above-average academic performance, social commitment, and alignment with democratic and Christian-democratic values. Foreign applicants must have a strong command of German.'),

-- Australia
('Australia Awards Scholarships', 'Australia', 'Agriculture', 'masters', '2026-04-30', 'https://www.australiaawards.gov.au/', 'Australia Awards Scholarships are long-term awards funded by the Australian Government and administered by the Department of Foreign Affairs and Trade (DFAT). They provide citizens from eligible developing countries in the Indo-Pacific, Africa, and the Middle East with the opportunity to undertake full-time undergraduate or postgraduate study at participating Australian universities. The scholarship covers full tuition fees, return airfare, an establishment allowance, a monthly living stipend, health cover through Overseas Student Health Cover (OSHC), and academic support. In the field of agriculture, Australia Awards scholars gain access to world-leading research institutions and practical training opportunities that address food security, sustainable farming, and rural development challenges directly relevant to their home countries. Scholars are expected to return home after completing their studies and use their skills to contribute to development.', 'Open to citizens of eligible countries in the Indo-Pacific region, Africa, and the Middle East. Applicants must not hold Australian or New Zealand citizenship or permanent residency, must be outside Australia at the time of application, and must commit to returning to their home country for at least two years after completing their studies.'),

('Endeavour Leadership Program', 'Australia', 'Environmental Science', 'phd', '2026-06-30', 'https://internationaleducation.gov.au/', 'The Endeavour Leadership Program is the Australian Government''s internationally competitive, merit-based scholarship programme providing opportunities for Australians to undertake study, research, or professional development abroad, and for overseas citizens to do the same in Australia. For international applicants, the Endeavour Research Fellowship and Postgraduate Scholarship streams support high-achieving individuals to conduct PhD or postdoctoral research at Australian institutions for up to four years. Scholars in environmental science gain access to Australia''s world-class research infrastructure in marine ecology, climate science, biodiversity, and sustainability. Benefits include a monthly stipend, establishment allowance, travel allowance, tuition fees, and health and travel insurance. Recipients are selected on the basis of academic excellence, research quality, and demonstrated commitment to their field.', 'Open to citizens of eligible countries in the Asia-Pacific, Middle East, Europe, and Americas regions. Applicants must not be Australian citizens or permanent residents. Candidates must demonstrate high academic achievement and the capacity to contribute to their community. The scholarship requires full-time enrolment at an Australian institution.'),

-- Canada
('Vanier Canada Graduate Scholarships', 'Canada', 'Medicine & Health', 'phd', '2026-11-01', 'https://vanier.gc.ca/', 'The Vanier Canada Graduate Scholarships (Vanier CGS) programme was created to attract and retain world-class doctoral students and to establish Canada as a global centre of excellence in research and higher education. Valued at $50,000 per year for three years, Vanier CGS is awarded to doctoral students who demonstrate strong academic achievement, research potential, and leadership ability. The programme is administered by Canada''s three federal research agencies — CIHR, NSERC, and SSHRC — and is available to both Canadian and international students at eligible Canadian universities. In Medicine and Health, Vanier scholars pursue cutting-edge doctoral research in areas including clinical trials, health systems, epidemiology, biomedical science, and global health. Recipients benefit from institutional support, networking events, and recognition as part of Canada''s most elite community of graduate researchers.', 'Open to both Canadian and international students who are nominated by a Canadian university. Candidates must be pursuing their first doctoral degree, have an overall average of at least A- in the last two completed years of study, and demonstrate leadership ability and a high standard of scholarly achievement in graduate and undergraduate studies.'),

('Trudeau Foundation Scholarship', 'Canada', 'Social Sciences', 'phd', '2026-12-01', 'https://www.trudeaufoundation.ca/', 'The Pierre Elliott Trudeau Foundation Scholarship is one of Canada''s most distinguished doctoral awards, recognising scholars whose research engages directly with pressing public policy questions and whose work holds the potential to positively impact Canadian and global society. Up to 15 scholars are selected annually from a highly competitive pool of applicants from across Canada. The scholarship provides a $60,000 annual award for up to four years, supplemented by a $20,000 travel and professional development allowance per year. Scholars work within the Foundation''s four thematic areas: engaged citizenship, human rights and dignity, responsible citizenship, and people and their natural environment. Beyond funding, scholars participate in intensive annual retreats, mentorship from Foundation Fellows, and a vibrant intellectual community of past and present scholars who shape the national conversation.', 'Open to Canadian citizens, permanent residents, and protected persons enrolled in or applying to a doctoral programme at a Canadian university. Research must engage with at least one of the Foundation''s four thematic areas. Applicants must demonstrate academic excellence, social commitment, and a vision for Canada''s role in the world.'),

-- Netherlands
('Holland Scholarship', 'Netherlands', 'Business', 'masters', '2027-01-31', 'https://www.studyinholland.nl/scholarships/', 'The Holland Scholarship is funded by the Dutch Ministry of Education, Culture and Science and offered by Dutch research universities and universities of applied sciences to attract talented students from outside the European Economic Area. The scholarship provides a one-time grant of EUR 5,000 to help cover the costs of the first year of a bachelor''s or master''s programme in the Netherlands. The Netherlands is consistently ranked among the world''s top education destinations, and its universities offer a wide range of English-taught business and management programmes at institutions such as the University of Amsterdam, Erasmus University Rotterdam, and Maastricht University. Studying in the Netherlands provides access to one of Europe''s strongest economies, a diverse international student community, and excellent professional networks in trade, logistics, finance, and technology.', 'Open to non-EEA international students who are applying to a full-time bachelor''s or master''s programme at a participating Dutch research university or university of applied sciences. Applicants must be applying for the first time to a Dutch higher education institution. Previous degree holders from the Netherlands are not eligible.'),

('Leiden Excellence Scholarship', 'Netherlands', 'Law', 'masters', '2026-09-01', 'https://www.universiteitleiden.nl/scholarships/', 'The Leiden Excellence Scholarship (LExS) is a merit-based award offered by Leiden University — one of Europe''s oldest and most prestigious universities, founded in 1575 — to outstanding international students from outside the European Economic Area. The scholarship supports students pursuing an English-taught master''s programme at Leiden University and is available in three tiers: a 50% tuition waiver, a 75% tuition waiver, or a 100% tuition waiver covering the full statutory tuition fee. Leiden University''s Law Faculty is internationally renowned, ranked among the top law schools globally, and offers specialisms in public international law, European law, criminal law, and legal theory. LExS recipients benefit from Leiden''s rich intellectual tradition, small class sizes, and a global alumni network that spans government, international organisations, and leading law firms.', 'Open to non-EEA students who have been admitted to a Leiden University English-taught master''s programme. Applicants must have completed a bachelor''s degree with outstanding academic results (typically a GPA in the top 10% of their class). The scholarship cannot be combined with other Leiden University scholarships.'),

-- Japan
('MEXT Scholarship', 'Japan', 'Engineering', 'masters', '2026-05-31', 'https://www.studyinjapan.go.jp/en/stype/mext/', 'The Japanese Government (MEXT) Scholarship is offered by Japan''s Ministry of Education, Culture, Sports, Science and Technology to international students who wish to study at Japanese universities as research students, undergraduate students, or students in specialised training colleges. For graduate-level engineering research, the scholarship typically covers full tuition fees, a monthly stipend of approximately ¥143,000 (research students) to ¥145,000 (master''s students), and return airfare. Recipients also complete a Japanese language preparation course before beginning their studies. Japan is a global leader in robotics, civil engineering, electrical engineering, and materials science, and MEXT scholars gain access to world-class laboratories and industry partnerships at universities such as Tokyo Institute of Technology, Osaka University, and Tohoku University. The scholarship period is typically two years for a master''s degree, with the possibility of extension.', 'Open to nationals of countries with diplomatic relations with Japan. Applicants must be under 35 years of age (for research students), have completed or be completing undergraduate education, and demonstrate Japanese language ability or willingness to learn. Applications are submitted via the Japanese Embassy in the applicant''s home country.'),

('JASSO Honors Scholarship', 'Japan', 'Natural Sciences', 'phd', '2026-08-31', 'https://www.jasso.or.jp/en/', 'The Japan Student Services Organization (JASSO) Honors Scholarship for Privately-Financed International Students provides monthly financial support to international students enrolled as regular students at Japanese universities, graduate schools, junior colleges, or colleges of technology. The scholarship is intended to assist outstanding international students who are self-financing their education in Japan and face financial difficulty. Monthly awards range from ¥48,000 for undergraduate students to ¥65,000 for graduate students. In the natural sciences, JASSO scholars are embedded in Japan''s leading research ecosystem, which ranks among the world''s top five in scientific output and is home to Nobel Prize-winning research in physics, chemistry, and medicine. Scholars benefit from structured mentorship, access to university research facilities, and a network connecting them with Japan''s vibrant scientific and academic community.', 'Open to international students currently enrolled at a Japanese university as regular students. Candidates must demonstrate excellent academic performance, strong conduct, and financial need. Recipients must maintain satisfactory academic progress throughout the scholarship period and must not be receiving other Japanese government scholarships simultaneously.'),

-- Switzerland
('Swiss Government Excellence Scholarships', 'Switzerland', 'Natural Sciences', 'phd', '2026-12-15', 'https://www.sbfi.admin.ch/scholarships/', 'The Swiss Government Excellence Scholarships are awarded by the Swiss Confederation to promote international exchange and research cooperation between Switzerland and over 180 countries. The scholarships are offered to postgraduate researchers, PhD candidates, and artists for study and research at Swiss public universities or recognised institutions. Recipients benefit from full coverage of living expenses via a monthly stipend of CHF 1,920, exemption from cantonal tuition fees at Swiss universities, a health insurance contribution, and accommodation support. Switzerland hosts four of the world''s top 15 universities — ETH Zurich, EPFL, University of Zurich, and the University of Basel — making it one of the most sought-after destinations for natural sciences research globally. Scholars are selected on scientific merit and the quality of their research proposal, with admission subject to acceptance by a Swiss academic host.', 'Open to citizens of eligible countries who hold a master''s degree (for PhD applicants) or a PhD (for postdoctoral applicants). Candidates must be no older than 35 years for PhD scholarships and 45 years for postdoctoral fellowships. Swiss citizens and current residents of Switzerland are not eligible. Applications are submitted through the Swiss Embassy.'),

-- Sweden
('Swedish Institute Scholarships', 'Sweden', 'Environmental Science', 'masters', '2027-02-10', 'https://si.se/en/apply/scholarships/', 'The Swedish Institute Scholarships for Global Professionals (SISGP) is a highly competitive scholarship programme that funds international professionals to pursue a one- or two-year master''s degree at a Swedish university. The scholarship covers full tuition fees, a monthly living allowance of SEK 11,000, travel grants, and insurance. Sweden is a world leader in sustainable development, clean technology, and environmental policy, and Swedish universities consistently rank among the best globally for environmental science, urban planning, and climate research. Beyond academic study, SI scholars participate in the Sweden-based SI Network for Future Global Leaders — a curated leadership programme offering workshops, study visits, meetings with Swedish industry leaders, and a mentorship scheme. The programme has a clear vision of developing a global network of leaders committed to sustainability and positive change.', 'Open to citizens of eligible countries in Asia, Africa, the Middle East, Eastern Europe, and Latin America. Applicants must have a bachelor''s degree, at least 3,000 hours of work experience, and demonstrate leadership potential and a commitment to contributing to sustainable development in their home country after completing the degree.'),

-- Singapore
('NUS Research Scholarship', 'Singapore', 'Computer Science', 'phd', '2027-03-01', 'https://nusgs.nus.edu.sg/scholarships/', 'The NUS Research Scholarship (NRS) is offered by the National University of Singapore — consistently ranked Asia''s top university and among the world''s top 15 globally — to attract outstanding students to pursue doctoral research across all disciplines. The scholarship provides full tuition fee subsidy, a monthly stipend of SGD 2,000 (enhanced to SGD 2,500 for students who have passed their qualifying examination), and a generous housing allowance. NUS''s School of Computing is one of the top-ranked computer science faculties in the world, with research strengths spanning artificial intelligence, cybersecurity, data science, human-computer interaction, and distributed systems. PhD students work closely with internationally recognised faculty, have access to state-of-the-art research labs, and benefit from NUS''s deep industry partnerships with global technology companies including Google, Microsoft, Alibaba, and Sea Group.', 'Open to both Singapore citizens and international applicants who have been admitted to an NUS PhD programme. Applicants must hold a good bachelor''s degree with honours (upper second class or equivalent) or a master''s degree in a relevant field. Proficiency in English is required. The scholarship is tenable for up to four years subject to satisfactory academic progress.')
on conflict (link) do update set
  title = excluded.title,
  description = excluded.description,
  eligibility = excluded.eligibility,
  deadline = excluded.deadline;
