-- Update eligibility for existing scholarship rows
update public.scholarships set eligibility = 'Open to citizens of participating countries outside the US. Applicants must hold a bachelor''s degree or equivalent, demonstrate English proficiency, and show strong academic and leadership records. US citizenship or permanent residency is not eligible. Selected candidates must commit to returning to their home country after completion.' where link = 'https://foreign.fulbrightonline.org/';

update public.scholarships set eligibility = 'Open to US citizens, nationals, and permanent residents who are in the early stages of their graduate study (first or second year). Applicants must be pursuing a research-based master''s or doctoral degree in an NSF-supported STEM field. Students who have completed more than 12 months of graduate study are ineligible.' where link = 'https://www.nsfgrfp.org/';

update public.scholarships set eligibility = 'Applicants must be African American, American Indian/Alaska Native, Asian Pacific Islander American, or Hispanic American; be a US citizen, national, or permanent resident; maintain a cumulative GPA of 3.3 or above; and demonstrate significant financial need as defined by federal guidelines.' where link = 'https://gmsp.org/';

update public.scholarships set eligibility = 'Open to applicants worldwide who have received their first undergraduate degree within the past seven years. Applicants must be admitted to a Stanford graduate degree programme. There are no restrictions on nationality, field of study, age, or professional background. Selection is based on independence of thought, purposeful leadership, and civic mindset.' where link = 'https://knight-hennessy.stanford.edu/';

update public.scholarships set eligibility = 'Applicants must be citizens of a Chevening-eligible country, have at least two years of work experience, hold an undergraduate degree that will gain entry to a UK university, and be able to return to their home country for a minimum of two years after the scholarship ends. Previous Chevening Scholars and current UK residents are not eligible.' where link = 'https://www.chevening.org/';

update public.scholarships set eligibility = 'Open to young people from eligible countries who are typically between 18–28 years of age (varies by constituency). Candidates must demonstrate intellectual distinction, character, leadership, and commitment to service. Applicants must hold or expect to hold a bachelor''s degree before taking up the scholarship.' where link = 'https://www.rhodeshouse.ox.ac.uk/';

update public.scholarships set eligibility = 'Open to citizens and permanent residents of Commonwealth countries applying to study at a UK university. Applicants must hold a first degree of at least upper second class (2:1) standard, be unable to pursue the study without the scholarship, and be available to take up the award by the start of the UK academic year.' where link = 'https://cscuk.fcdo.gov.uk/';

update public.scholarships set eligibility = 'Open to international students who hold an above-average bachelor''s degree. Applicants typically need at least two years of professional experience after completing their first academic degree. German language skills may be required depending on the programme. Applications must be submitted through the applicant''s home country DAAD office.' where link = 'https://www.daad.de/en/';

update public.scholarships set eligibility = 'Open to German and foreign students enrolled in or applying for a doctoral programme at a German university. Applicants must demonstrate above-average academic performance, social commitment, and alignment with democratic values. Foreign applicants must have a strong command of German.' where link = 'https://www.kas.de/en/';

update public.scholarships set eligibility = 'Open to citizens of eligible countries in the Indo-Pacific region, Africa, and the Middle East. Applicants must not hold Australian or New Zealand citizenship or permanent residency, must be outside Australia at the time of application, and must commit to returning to their home country for at least two years after completing their studies.' where link = 'https://www.australiaawards.gov.au/';

update public.scholarships set eligibility = 'Open to citizens of eligible countries in the Asia-Pacific, Middle East, Europe, and Americas regions. Applicants must not be Australian citizens or permanent residents. Candidates must demonstrate high academic achievement and the capacity to contribute to their community. The scholarship requires full-time enrolment at an Australian institution.' where link = 'https://internationaleducation.gov.au/';

update public.scholarships set eligibility = 'Open to both Canadian and international students nominated by a Canadian university. Candidates must be pursuing their first doctoral degree, have an overall average of at least A- in the last two completed years of study, and demonstrate leadership ability and high scholarly achievement in graduate and undergraduate studies.' where link = 'https://vanier.gc.ca/';

update public.scholarships set eligibility = 'Open to Canadian citizens, permanent residents, and protected persons enrolled in or applying to a doctoral programme at a Canadian university. Research must engage with at least one of the Foundation''s four thematic areas. Applicants must demonstrate academic excellence, social commitment, and a vision for Canada''s role in the world.' where link = 'https://www.trudeaufoundation.ca/';

update public.scholarships set eligibility = 'Open to non-EEA international students applying to a full-time bachelor''s or master''s programme at a participating Dutch research university or university of applied sciences. Applicants must be applying for the first time to a Dutch higher education institution. Previous degree holders from the Netherlands are not eligible.' where link = 'https://www.studyinholland.nl/scholarships/';

update public.scholarships set eligibility = 'Open to non-EEA students admitted to a Leiden University English-taught master''s programme. Applicants must have completed a bachelor''s degree with outstanding academic results (typically a GPA in the top 10% of their class). The scholarship cannot be combined with other Leiden University scholarships.' where link = 'https://www.universiteitleiden.nl/scholarships/';

update public.scholarships set eligibility = 'Open to nationals of countries with diplomatic relations with Japan. Applicants must be under 35 years of age (for research students), have completed or be completing undergraduate education, and demonstrate Japanese language ability or willingness to learn. Applications are submitted via the Japanese Embassy in the applicant''s home country.' where link = 'https://www.studyinjapan.go.jp/en/stype/mext/';

update public.scholarships set eligibility = 'Open to international students currently enrolled at a Japanese university as regular students. Candidates must demonstrate excellent academic performance, strong conduct, and financial need. Recipients must maintain satisfactory academic progress and must not be receiving other Japanese government scholarships simultaneously.' where link = 'https://www.jasso.or.jp/en/';

update public.scholarships set eligibility = 'Open to citizens of eligible countries who hold a master''s degree (for PhD applicants) or a PhD (for postdoctoral applicants). Candidates must be no older than 35 years for PhD scholarships and 45 years for postdoctoral fellowships. Swiss citizens and current residents of Switzerland are not eligible. Applications are submitted through the Swiss Embassy.' where link = 'https://www.sbfi.admin.ch/scholarships/';

update public.scholarships set eligibility = 'Open to citizens of eligible countries in Asia, Africa, the Middle East, Eastern Europe, and Latin America. Applicants must have a bachelor''s degree, at least 3,000 hours of work experience, and demonstrate leadership potential and a commitment to contributing to sustainable development in their home country after completing the degree.' where link = 'https://si.se/en/apply/scholarships/';

update public.scholarships set eligibility = 'Open to both Singapore citizens and international applicants admitted to an NUS PhD programme. Applicants must hold a good bachelor''s degree with honours (upper second class or equivalent) or a master''s degree in a relevant field. Proficiency in English is required. The scholarship is tenable for up to four years subject to satisfactory academic progress.' where link = 'https://nusgs.nus.edu.sg/scholarships/';
